name: nemuru
description: NEMURU - A sleep and mental wellness app
publish_to: 'none'
version: 1.0.6+7

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.3
  google_fonts: ^4.0.4
  table_calendar: ^3.0.9
  flutter_svg: ^2.0.7
  timezone: ^0.9.2
  uuid: ^3.0.7
  package_info_plus: ^4.0.2
  url_launcher: ^6.3.1
  flutter_markdown: ^0.6.14
  in_app_purchase: ^3.1.5
  in_app_purchase_storekit: ^0.3.6+3
  in_app_purchase_android: ^0.3.0+10
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

